// Mock data for UI scaffold (B3). Will be replaced by real data layer (B2/B7).
// IDs are stable strings so recipe.ingredients[].ingredientId references resolve.

import type {
  Ingredient,
  RecipeWithRelations,
  Recipe,
  RecipeIngredient,
  RecipeStep,
  Technique,
} from "./types";

// ─── Ingredients ─────────────────────────────────────────────────────────────

export const mockIngredients: Ingredient[] = [
  // Base spirits
  {
    id: "ing-gin",
    slug: "gin",
    nameZh: "金酒",
    nameEn: "Gin",
    category: "BASE_SPIRIT",
    abv: 40,
    flavorTags: ["juniper", "botanical", "citrus"],
    colorHex: "#E8F0E8",
    descriptionZh: "以杜松子为主要香料的蒸馏酒",
    descriptionEn: "Botanical-forward distilled spirit with juniper at the core",
  },
  {
    id: "ing-bourbon",
    slug: "bourbon",
    nameZh: "波本威士忌",
    nameEn: "Bourbon Whiskey",
    category: "BASE_SPIRIT",
    abv: 45,
    flavorTags: ["vanilla", "caramel", "oak"],
    colorHex: "#C8893A",
    descriptionZh: "美国玉米为主的威士忌，带香草与焦糖风味",
    descriptionEn: "American corn-forward whiskey with vanilla and caramel notes",
  },
  {
    id: "ing-white-rum",
    slug: "white-rum",
    nameZh: "白朗姆酒",
    nameEn: "White Rum",
    category: "BASE_SPIRIT",
    abv: 40,
    flavorTags: ["sweet", "tropical", "light"],
    colorHex: "#F4F1E8",
    descriptionZh: "清淡甘蔗蒸馏酒",
    descriptionEn: "Light, clean sugarcane distillate",
  },
  {
    id: "ing-vodka",
    slug: "vodka",
    nameZh: "伏特加",
    nameEn: "Vodka",
    category: "BASE_SPIRIT",
    abv: 40,
    flavorTags: ["neutral", "clean"],
    colorHex: "#F0F0F0",
    descriptionZh: "中性无色蒸馏酒",
    descriptionEn: "Neutral, clean distilled spirit",
  },
  {
    id: "ing-tequila-blanco",
    slug: "tequila-blanco",
    nameZh: "银龙舌兰",
    nameEn: "Tequila Blanco",
    category: "BASE_SPIRIT",
    abv: 40,
    flavorTags: ["agave", "citrus", "earthy"],
    colorHex: "#EDE9DC",
    descriptionZh: "未经陈年的龙舌兰酒",
    descriptionEn: "Unaged agave spirit with bright citrus notes",
  },

  // Liqueurs
  {
    id: "ing-campari",
    slug: "campari",
    nameZh: "金巴利",
    nameEn: "Campari",
    category: "LIQUEUR",
    abv: 25,
    flavorTags: ["bitter", "herbal", "citrus"],
    colorHex: "#B33A3A",
    descriptionZh: "意大利苦味开胃酒",
    descriptionEn: "Italian bitter aperitivo with herbal citrus notes",
  },
  {
    id: "ing-sweet-vermouth",
    slug: "sweet-vermouth",
    nameZh: "甜味美思",
    nameEn: "Sweet Vermouth",
    category: "WINE",
    abv: 16,
    flavorTags: ["sweet", "herbal", "spice"],
    colorHex: "#7B2D26",
    descriptionZh: "加香加强葡萄酒",
    descriptionEn: "Aromatized fortified wine with herbs and spice",
  },
  {
    id: "ing-dry-vermouth",
    slug: "dry-vermouth",
    nameZh: "干味美思",
    nameEn: "Dry Vermouth",
    category: "WINE",
    abv: 18,
    flavorTags: ["dry", "herbal", "floral"],
    colorHex: "#F2F0E6",
    descriptionZh: "干型加香葡萄酒",
    descriptionEn: "Dry white aromatized wine with floral botanicals",
  },
  {
    id: "ing-triple-sec",
    slug: "triple-sec",
    nameZh: "橙皮酒",
    nameEn: "Triple Sec",
    category: "LIQUEUR",
    abv: 30,
    flavorTags: ["orange", "sweet", "citrus"],
    colorHex: "#F2A93B",
    descriptionZh: "橙味利口酒",
    descriptionEn: "Clear orange-flavored liqueur",
  },

  // Juices
  {
    id: "ing-lemon-juice",
    slug: "lemon-juice",
    nameZh: "柠檬汁",
    nameEn: "Lemon Juice",
    category: "JUICE",
    abv: null,
    flavorTags: ["sour", "citrus", "fresh"],
    colorHex: "#F4E45C",
    descriptionZh: "新鲜柠檬压榨汁",
    descriptionEn: "Freshly squeezed lemon juice",
  },
  {
    id: "ing-lime-juice",
    slug: "lime-juice",
    nameZh: "青柠汁",
    nameEn: "Lime Juice",
    category: "JUICE",
    abv: null,
    flavorTags: ["sour", "citrus", "fresh"],
    colorHex: "#A8C957",
    descriptionZh: "新鲜青柠压榨汁",
    descriptionEn: "Freshly squeezed lime juice",
  },

  // Syrups
  {
    id: "ing-simple-syrup",
    slug: "simple-syrup",
    nameZh: "单糖浆",
    nameEn: "Simple Syrup",
    category: "SYRUP",
    abv: null,
    flavorTags: ["sweet"],
    colorHex: "#F0F0E8",
    descriptionZh: "1:1 糖水",
    descriptionEn: "1:1 sugar-water syrup",
  },
  {
    id: "ing-honey-syrup",
    slug: "honey-syrup",
    nameZh: "蜂蜜糖浆",
    nameEn: "Honey Syrup",
    category: "SYRUP",
    abv: null,
    flavorTags: ["sweet", "floral"],
    colorHex: "#D4A847",
    descriptionZh: "蜂蜜与水 1:1 稀释",
    descriptionEn: "1:1 honey and water dilution",
  },

  // Bitters
  {
    id: "ing-angostura",
    slug: "angostura-bitters",
    nameZh: "安格斯特拉苦精",
    nameEn: "Angostura Bitters",
    category: "BITTERS",
    abv: 45,
    flavorTags: ["bitter", "spice", "aromatic"],
    colorHex: "#4A2A1A",
    descriptionZh: "经典芳香型苦精",
    descriptionEn: "Classic aromatic bitters",
  },
  {
    id: "ing-orange-bitters",
    slug: "orange-bitters",
    nameZh: "橙味苦精",
    nameEn: "Orange Bitters",
    category: "BITTERS",
    abv: 40,
    flavorTags: ["bitter", "orange", "citrus"],
    colorHex: "#D88840",
    descriptionZh: "橙皮调味的苦精",
    descriptionEn: "Orange-peel-forward aromatic bitters",
  },

  // Dairy / Egg
  {
    id: "ing-egg-white",
    slug: "egg-white",
    nameZh: "蛋清",
    nameEn: "Egg White",
    category: "DAIRY",
    abv: null,
    flavorTags: ["silky", "foam"],
    colorHex: "#FFFCEF",
    descriptionZh: "新鲜鸡蛋蛋清",
    descriptionEn: "Fresh egg white for texture and foam",
  },

  // Herbs & Garnish
  {
    id: "ing-mint",
    slug: "mint",
    nameZh: "薄荷叶",
    nameEn: "Mint",
    category: "HERB_SPICE",
    abv: null,
    flavorTags: ["fresh", "aromatic", "cool"],
    colorHex: "#5C8A4A",
    descriptionZh: "新鲜薄荷叶",
    descriptionEn: "Fresh mint leaves",
  },
  {
    id: "ing-cherry",
    slug: "cherry",
    nameZh: "马拉斯奇诺樱桃",
    nameEn: "Maraschino Cherry",
    category: "GARNISH",
    abv: null,
    flavorTags: ["sweet", "fruit"],
    colorHex: "#B33A3A",
    descriptionZh: "酒渍樱桃",
    descriptionEn: "Brined maraschino cherry",
  },
  {
    id: "ing-orange-peel",
    slug: "orange-peel",
    nameZh: "橙皮",
    nameEn: "Orange Peel",
    category: "GARNISH",
    abv: null,
    flavorTags: ["citrus", "aromatic"],
    colorHex: "#F2A93B",
    descriptionZh: "新鲜橙皮卷或条",
    descriptionEn: "Fresh orange peel, twisted or cut",
  },
];

// ─── Techniques (subset for preview) ─────────────────────────────────────────

const techniques: Technique[] = [
  {
    id: "tech-stir",
    slug: "stir",
    nameZh: "搅拌",
    nameEn: "Stir",
    category: "STIR",
    descriptionZh: "用吧勺搅拌冰块与酒液",
    descriptionEn: "Stir ingredients with ice using a bar spoon",
    stepsZh: ["加冰入搅拌杯", "注入酒液", "顺时针搅拌 30 次", "滤入杯中"],
    stepsEn: ["Add ice to mixing glass", "Pour liquids", "Stir 30 rotations", "Strain into glass"],
    tipsZh: ["保持勺背贴壁旋转", "酒液降温约 5-8°C"],
    tipsEn: ["Keep the spoon back against the glass", "Aim for 5-8°C of dilution"],
    warningsZh: ["过度搅拌会过度稀释"],
    warningsEn: ["Over-stirring over-dilutes the drink"],
  },
  {
    id: "tech-shake",
    slug: "shake",
    nameZh: "摇和",
    nameEn: "Shake",
    category: "SHAKE",
    descriptionZh: "在雪克壶中剧烈摇动以充分混合并乳化",
    descriptionEn: "Vigorous shaking in a shaker for mixing and emulsification",
    stepsZh: ["所有材料入雪克壶", "加冰至 2/3", "先轻摇排气，再剧烈摇 10-12 秒", "双重过滤入杯"],
    stepsEn: ["Add all ingredients to shaker", "Fill 2/3 with ice", "Shake hard 10-12 seconds", "Double-strain into glass"],
    tipsZh: ["含蛋清时先干摇 10 秒再湿摇", "摇壶外结霜即到位"],
    tipsEn: ["Dry-shake with egg white first", "Frost on the shaker = ready"],
    warningsZh: ["摇动时间过短导致混合不均"],
    warningsEn: ["Under-shaking yields poor integration"],
  },
  {
    id: "tech-muddle",
    slug: "muddle",
    nameZh: "捣压",
    nameEn: "Muddle",
    category: "MUDDLE",
    descriptionZh: "用捣棒轻柔释放植物香气",
    descriptionEn: "Gently press herbs or fruit to release aromatics",
    stepsZh: ["薄荷等放入杯底", "轻压 3-4 次", "避免撕碎叶片"],
    stepsEn: ["Place mint or fruit in glass", "Press 3-4 times gently", "Avoid tearing leaves"],
    tipsZh: ["薄荷只需轻压，避免苦味"],
    tipsEn: ["Gentle pressure preserves mint freshness"],
    warningsZh: ["过度捣压会释放苦味单宁"],
    warningsEn: ["Over-muddling releases bitter tannins"],
  },
  {
    id: "tech-build",
    slug: "build",
    nameZh: "直调",
    nameEn: "Build",
    category: "BUILD",
    descriptionZh: "在杯中直接加入所有材料并搅拌",
    descriptionEn: "Combine ingredients directly in the serving glass",
    stepsZh: ["杯中加冰", "依次倒入材料", "轻柔搅拌"],
    stepsEn: ["Add ice to glass", "Pour each ingredient", "Stir gently"],
    tipsZh: ["长饮类常用直调法"],
    tipsEn: ["Standard for highballs and sours"],
    warningsZh: [],
    warningsEn: [],
  },
  {
    id: "tech-strain",
    slug: "strain",
    nameZh: "过滤",
    nameEn: "Strain",
    category: "STRAIN",
    descriptionZh: "用滤冰器或细滤网分离冰渣与残渣",
    descriptionEn: "Separate ice and solids from the finished drink",
    stepsZh: ["握住滤冰器", "缓缓倒入", "细滤去除碎冰"],
    stepsEn: ["Hold a Hawthorne strainer", "Pour steadily", "Use a fine mesh for clarity"],
    tipsZh: ["双重过滤可获丝绸口感"],
    tipsEn: ["Double-strain for silky texture"],
    warningsZh: [],
    warningsEn: [],
  },
  {
    id: "tech-garnish",
    slug: "garnish",
    nameZh: "装饰",
    nameEn: "Garnish",
    category: "GARNISH",
    descriptionZh: "用香气和视觉完成鸡尾酒",
    descriptionEn: "Final aromatic and visual touch",
    stepsZh: ["选择与配方匹配的装饰", "擦拭杯沿油脂", "置于杯口或液面"],
    stepsEn: ["Choose a complementary garnish", "Express oils over the rim", "Place on rim or surface"],
    tipsZh: ["橙皮挤油能显著提升香气"],
    tipsEn: ["Expressed oils amplify the aroma"],
    warningsZh: [],
    warningsEn: [],
  },
];

// ─── Recipes ─────────────────────────────────────────────────────────────────

const oldFashioned: Recipe = {
  id: "recipe-old-fashioned",
  slug: "old-fashioned",
  nameZh: "古典鸡尾酒",
  nameEn: "Old Fashioned",
  type: "CLASSIC",
  difficulty: 2,
  glassType: "Old Fashioned / Rocks",
  iceType: "Large cube",
  descriptionZh: "威士忌、糖与苦精的经典组合，简单却深邃。",
  descriptionEn: "Whiskey, sugar, and bitters — the original cocktail template.",
  storyNoteZh: "19 世纪末的俱乐部经典，象征美式鸡尾酒的本源。",
  storyNoteEn: "A 19th-century club classic, the ur-American cocktail.",
  balanceTags: ["spirit-forward", "bitter-sweet"],
};

const oldFashionedIngredients: RecipeIngredient[] = [
  {
    id: "ri-of-bourbon",
    recipeId: oldFashioned.id,
    ingredientId: "ing-bourbon",
    amount: "60 ml",
    isKey: true,
    optional: false,
    notesZh: "推荐波本或黑麦",
    notesEn: "Bourbon or rye preferred",
    order: 0,
  },
  {
    id: "ri-of-sugar",
    recipeId: oldFashioned.id,
    ingredientId: "ing-simple-syrup",
    amount: "5 ml",
    isKey: true,
    optional: false,
    notesZh: "可替换为方糖",
    notesEn: "Sub sugar cube if desired",
    order: 1,
  },
  {
    id: "ri-of-angostura",
    recipeId: oldFashioned.id,
    ingredientId: "ing-angostura",
    amount: "2 dashes",
    isKey: true,
    optional: false,
    notesZh: "或加入橙味苦精",
    notesEn: "Or add a dash of orange bitters",
    order: 2,
  },
  {
    id: "ri-of-orange-peel",
    recipeId: oldFashioned.id,
    ingredientId: "ing-orange-peel",
    amount: "1 piece",
    isKey: false,
    optional: true,
    notesZh: "挤油装饰",
    notesEn: "Express oils for garnish",
    order: 3,
  },
  {
    id: "ri-of-cherry",
    recipeId: oldFashioned.id,
    ingredientId: "ing-cherry",
    amount: "1 piece",
    isKey: false,
    optional: true,
    notesZh: "酒渍樱桃",
    notesEn: "Luxardo-style cherry",
    order: 4,
  },
];

const oldFashionedSteps: RecipeStep[] = [
  {
    id: "rs-of-1",
    recipeId: oldFashioned.id,
    order: 0,
    instructionZh: "在搅拌杯中加入糖浆与苦精",
    instructionEn: "Add syrup and bitters to a mixing glass",
    duration: null,
    techniqueId: "tech-build",
    tipZh: "先稀释苦精便于分散",
    tipEn: "Pre-dilute bitters to spread evenly",
  },
  {
    id: "rs-of-2",
    recipeId: oldFashioned.id,
    order: 1,
    instructionZh: "加冰与波本，搅拌降温",
    instructionEn: "Add ice and bourbon, stir to chill",
    duration: "30 sec",
    techniqueId: "tech-stir",
    tipZh: "顺时针 30 圈",
    tipEn: "30 clockwise rotations",
  },
  {
    id: "rs-of-3",
    recipeId: oldFashioned.id,
    order: 2,
    instructionZh: "滤入装有大方冰的洛克杯",
    instructionEn: "Strain over a large ice cube in a rocks glass",
    duration: null,
    techniqueId: "tech-strain",
    tipZh: null,
    tipEn: null,
  },
  {
    id: "rs-of-4",
    recipeId: oldFashioned.id,
    order: 3,
    instructionZh: "用橙皮挤油并以樱桃装饰",
    instructionEn: "Express orange peel and garnish with a cherry",
    duration: null,
    techniqueId: "tech-garnish",
    tipZh: "橙皮油脂点燃整个香气",
    tipEn: "Citrus oils ignite the aromatics",
  },
];

const daiquiri: Recipe = {
  id: "recipe-daiquiri",
  slug: "daiquiri",
  nameZh: "得其利",
  nameEn: "Daiquiri",
  type: "CLASSIC",
  difficulty: 2,
  glassType: "Coupe",
  iceType: "None (up)",
  descriptionZh: "古巴三剑客：朗姆、青柠、糖，简洁平衡。",
  descriptionEn: "Rum, lime, sugar — Cuba's perfect three-ingredient sour.",
  storyNoteZh: "由古巴矿工与美军医在 1898 年前后记录流传。",
  storyNoteEn: "Recorded in Cuba around 1898, a Hemingway favorite.",
  balanceTags: ["sour", "refreshing"],
};

const daiquiriIngredients: RecipeIngredient[] = [
  {
    id: "ri-dq-rum",
    recipeId: daiquiri.id,
    ingredientId: "ing-white-rum",
    amount: "60 ml",
    isKey: true,
    optional: false,
    notesZh: "白朗姆为佳",
    notesEn: "White rum preferred",
    order: 0,
  },
  {
    id: "ri-dq-lime",
    recipeId: daiquiri.id,
    ingredientId: "ing-lime-juice",
    amount: "22 ml",
    isKey: true,
    optional: false,
    notesZh: "现榨青柠",
    notesEn: "Freshly squeezed",
    order: 1,
  },
  {
    id: "ri-dq-sugar",
    recipeId: daiquiri.id,
    ingredientId: "ing-simple-syrup",
    amount: "15 ml",
    isKey: true,
    optional: false,
    notesZh: "可按口味增减",
    notesEn: "Adjust to taste",
    order: 2,
  },
];

const daiquiriSteps: RecipeStep[] = [
  {
    id: "rs-dq-1",
    recipeId: daiquiri.id,
    order: 0,
    instructionZh: "所有材料加入雪克壶",
    instructionEn: "Add all ingredients to a shaker",
    duration: null,
    techniqueId: "tech-shake",
    tipZh: "比例 3:1.1:0.75 为经典基准",
    tipEn: "Classic ratio is 3:1.1:0.75",
  },
  {
    id: "rs-dq-2",
    recipeId: daiquiri.id,
    order: 1,
    instructionZh: "加冰后剧烈摇 10-12 秒",
    instructionEn: "Add ice and shake hard for 10-12 seconds",
    duration: "12 sec",
    techniqueId: "tech-shake",
    tipZh: "摇壶外结霜即到位",
    tipEn: "Frost on the shaker signals readiness",
  },
  {
    id: "rs-dq-3",
    recipeId: daiquiri.id,
    order: 2,
    instructionZh: "双重过滤入冰镇 coupe 杯",
    instructionEn: "Double-strain into a chilled coupe",
    duration: null,
    techniqueId: "tech-strain",
    tipZh: "无冰上桌，避免稀释",
    tipEn: "Serve up — no ice in glass",
  },
  {
    id: "rs-dq-4",
    recipeId: daiquiri.id,
    order: 3,
    instructionZh: "可选青柠片或橙皮装饰",
    instructionEn: "Optional lime wheel or orange peel garnish",
    duration: null,
    techniqueId: "tech-garnish",
    tipZh: null,
    tipEn: null,
  },
];

const negroni: Recipe = {
  id: "recipe-negroni",
  slug: "negroni",
  nameZh: "尼格罗尼",
  nameEn: "Negroni",
  type: "CLASSIC",
  difficulty: 1,
  glassType: "Old Fashioned / Rocks",
  iceType: "Large cube",
  descriptionZh: "等比金酒、金巴利、甜味美思，苦甜平衡的意大利名片。",
  descriptionEn: "Equal parts gin, Campari, sweet vermouth — Italy's bittersweet icon.",
  storyNoteZh: "1919 年佛罗伦萨的 Count Negroni 改良自 Americano。",
  storyNoteEn: "Invented in 1919 Florence, a bolder take on the Americano.",
  balanceTags: ["bitter-sweet", "spirit-forward"],
};

const negroniIngredients: RecipeIngredient[] = [
  {
    id: "ri-ng-gin",
    recipeId: negroni.id,
    ingredientId: "ing-gin",
    amount: "30 ml",
    isKey: true,
    optional: false,
    notesZh: "伦敦干金为经典",
    notesEn: "London dry preferred",
    order: 0,
  },
  {
    id: "ri-ng-campari",
    recipeId: negroni.id,
    ingredientId: "ing-campari",
    amount: "30 ml",
    isKey: true,
    optional: false,
    notesZh: null,
    notesEn: null,
    order: 1,
  },
  {
    id: "ri-ng-vermouth",
    recipeId: negroni.id,
    ingredientId: "ing-sweet-vermouth",
    amount: "30 ml",
    isKey: true,
    optional: false,
    notesZh: "意大利甜型",
    notesEn: "Italian rosso",
    order: 2,
  },
  {
    id: "ri-ng-orange",
    recipeId: negroni.id,
    ingredientId: "ing-orange-peel",
    amount: "1 piece",
    isKey: false,
    optional: false,
    notesZh: "挤油装饰",
    notesEn: "Express oils for garnish",
    order: 3,
  },
];

const negroniSteps: RecipeStep[] = [
  {
    id: "rs-ng-1",
    recipeId: negroni.id,
    order: 0,
    instructionZh: "所有液体加入搅拌杯",
    instructionEn: "Combine all liquids in a mixing glass",
    duration: null,
    techniqueId: "tech-build",
    tipZh: "等比 1:1:1 黄金法则",
    tipEn: "Equal parts — 1:1:1",
  },
  {
    id: "rs-ng-2",
    recipeId: negroni.id,
    order: 1,
    instructionZh: "加冰后搅拌降温",
    instructionEn: "Add ice and stir to chill",
    duration: "20 sec",
    techniqueId: "tech-stir",
    tipZh: "搅拌而非摇动以保留澄澈",
    tipEn: "Stir — never shake — for clarity",
  },
  {
    id: "rs-ng-3",
    recipeId: negroni.id,
    order: 2,
    instructionZh: "滤入装有大方冰的洛克杯",
    instructionEn: "Strain over a large ice cube in a rocks glass",
    duration: null,
    techniqueId: "tech-strain",
    tipZh: null,
    tipEn: null,
  },
  {
    id: "rs-ng-4",
    recipeId: negroni.id,
    order: 3,
    instructionZh: "橙皮挤油装饰",
    instructionEn: "Garnish with expressed orange peel",
    duration: null,
    techniqueId: "tech-garnish",
    tipZh: "皮朝上摆放，杯口留香",
    tipEn: "Place peel skin-side up for aroma",
  },
];

const whiskeySour: Recipe = {
  id: "recipe-whiskey-sour",
  slug: "whiskey-sour",
  nameZh: "威士忌酸",
  nameEn: "Whiskey Sour",
  type: "CLASSIC",
  difficulty: 2,
  glassType: "Coupe or Rocks",
  iceType: "Optional cube",
  descriptionZh: "威士忌与柠檬的对话，蛋清带来丝绸般的泡沫。",
  descriptionEn: "Whiskey meets lemon — egg white adds a velvety foam cap.",
  storyNoteZh: "1862 年《The Bartender's Guide》首次记载。",
  storyNoteEn: "First printed in Jerry Thomas's 1862 Bartender's Guide.",
  balanceTags: ["sour", "silky"],
};

const whiskeySourIngredients: RecipeIngredient[] = [
  {
    id: "ri-ws-bourbon",
    recipeId: whiskeySour.id,
    ingredientId: "ing-bourbon",
    amount: "60 ml",
    isKey: true,
    optional: false,
    notesZh: "波本最经典",
    notesEn: "Bourbon is canonical",
    order: 0,
  },
  {
    id: "ri-ws-lemon",
    recipeId: whiskeySour.id,
    ingredientId: "ing-lemon-juice",
    amount: "22 ml",
    isKey: true,
    optional: false,
    notesZh: "现榨柠檬",
    notesEn: "Freshly squeezed",
    order: 1,
  },
  {
    id: "ri-ws-sugar",
    recipeId: whiskeySour.id,
    ingredientId: "ing-simple-syrup",
    amount: "15 ml",
    isKey: true,
    optional: false,
    notesZh: "或使用蜂蜜糖浆",
    notesEn: "Or honey syrup for variation",
    order: 2,
  },
  {
    id: "ri-ws-egg",
    recipeId: whiskeySour.id,
    ingredientId: "ing-egg-white",
    amount: "1 piece",
    isKey: false,
    optional: true,
    notesZh: "可省略",
    notesEn: "Optional but recommended",
    order: 3,
  },
  {
    id: "ri-ws-angostura",
    recipeId: whiskeySour.id,
    ingredientId: "ing-angostura",
    amount: "2 dashes",
    isKey: false,
    optional: true,
    notesZh: "泡沫顶部点饰",
    notesEn: "Drops on the foam cap",
    order: 4,
  },
];

const whiskeySourSteps: RecipeStep[] = [
  {
    id: "rs-ws-1",
    recipeId: whiskeySour.id,
    order: 0,
    instructionZh: "蛋清与液体加入雪克壶，无冰干摇 10 秒",
    instructionEn: "Combine egg white and liquids, dry-shake 10 seconds",
    duration: "10 sec",
    techniqueId: "tech-shake",
    tipZh: "干摇先乳化蛋清",
    tipEn: "Dry-shake emulsifies the egg white",
  },
  {
    id: "rs-ws-2",
    recipeId: whiskeySour.id,
    order: 1,
    instructionZh: "加冰再剧烈摇 12 秒",
    instructionEn: "Add ice and shake hard for 12 seconds",
    duration: "12 sec",
    techniqueId: "tech-shake",
    tipZh: "充分降温与稀释",
    tipEn: "Chill and dilute thoroughly",
  },
  {
    id: "rs-ws-3",
    recipeId: whiskeySour.id,
    order: 2,
    instructionZh: "双重过滤入冰镇 coupe 杯",
    instructionEn: "Double-strain into a chilled coupe",
    duration: null,
    techniqueId: "tech-strain",
    tipZh: null,
    tipEn: null,
  },
  {
    id: "rs-ws-4",
    recipeId: whiskeySour.id,
    order: 3,
    instructionZh: "泡沫上点几滴安格斯特拉苦精",
    instructionEn: "Drops of Angostura on the foam cap",
    duration: null,
    techniqueId: "tech-garnish",
    tipZh: "用牙签划出花纹",
    tipEn: "Drag a toothpick for a pattern",
  },
];

// ─── Composite (with relations) ──────────────────────────────────────────────

function attachRelations(
  recipe: Recipe,
  ingredients: RecipeIngredient[],
  steps: RecipeStep[],
): RecipeWithRelations {
  const techById = new Map(techniques.map((t) => [t.id, t]));
  return {
    ...recipe,
    ingredients: ingredients.map((ri) => {
      const ing = mockIngredients.find((i) => i.id === ri.ingredientId);
      if (!ing) throw new Error(`Mock ingredient not found: ${ri.ingredientId}`);
      return {
        ...ri,
        ingredient: {
          id: ing.id,
          nameZh: ing.nameZh,
          nameEn: ing.nameEn,
          category: ing.category,
          colorHex: ing.colorHex,
        },
      };
    }),
    steps: steps.map((rs) => ({
      ...rs,
      technique: rs.techniqueId
        ? (() => {
            const t = techById.get(rs.techniqueId);
            return t
              ? { id: t.id, nameZh: t.nameZh, nameEn: t.nameEn, category: t.category }
              : null;
          })()
        : null,
    })),
    techniques: Array.from(
      new Set(
        steps
          .map((s) => s.techniqueId)
          .filter((id): id is string => Boolean(id))
          .map((id) => techById.get(id))
          .filter((t): t is Technique => Boolean(t)),
      ),
    ).map((t) => ({
      id: t.id,
      nameZh: t.nameZh,
      nameEn: t.nameEn,
      category: t.category,
      slug: t.slug,
    })),
  };
}

export const mockRecipes: RecipeWithRelations[] = [
  attachRelations(oldFashioned, oldFashionedIngredients, oldFashionedSteps),
  attachRelations(daiquiri, daiquiriIngredients, daiquiriSteps),
  attachRelations(negroni, negroniIngredients, negroniSteps),
  attachRelations(whiskeySour, whiskeySourIngredients, whiskeySourSteps),
];

// ─── Lookup helpers ──────────────────────────────────────────────────────────

const ingredientIndex = new Map(mockIngredients.map((i) => [i.id, i]));

export function getMockIngredientById(id: string): Ingredient | undefined {
  return ingredientIndex.get(id);
}
